// Code generated by tygo. DO NOT EDIT.
// Code generated by tygo. DO NOT EDIT.
export type ServerMessage =
  | WelcomeMessage
  | GameStateMessage
  | CountdownMessage
  | BetAcceptedMessage
  | BetRejectedMessage
  | ResultMessage
  | BetPlacedMessage
  | PlayerListMessage
  | PlayerJoinedMessage
  | PlayerLeftMessage
  | PlayerBalanceUpdatedMessage;
export type ClientMessage =
  | PlaceBetAction
  | SetNameAction
  | ReconnectAction;

//////////
// source: messages.go

/**
 * GamePhase represents the current phase of a game round.
 */
export const GamePhaseBetting = "BETTING";
export const GamePhaseSpinning = "SPINNING";
export const GamePhaseResult = "RESULT";
export type GamePhase = typeof GamePhaseBetting | typeof GamePhaseSpinning | typeof GamePhaseResult;
/**
 * BetType represents the type of bet a player can place.
 */
export const BetTypeStraight = "straight";
export const BetTypeColor = "color";
export const BetTypeEvenOdd = "even_odd";
export const BetTypeDozens = "dozens";
export type BetType = typeof BetTypeStraight | typeof BetTypeColor | typeof BetTypeEvenOdd | typeof BetTypeDozens;
/**
 * Bet represents a single bet placed by a user.
 */
export interface Bet {
  user_id: string;
  type: BetType;
  value: string;
  amount: number /* int64 */;
}
/**
 * Payout represents the result of a bet after a spin.
 */
export interface Payout {
  bet: Bet;
  winnings: number /* int64 */;
}
/**
 * Player represents a connected player at the table.
 */
export interface Player {
  user_id: string;
  name: string;
  balance: number /* int64 */;
  connected: boolean;
}
export interface WelcomeMessage {
  type: 'welcome';
  user_id: string;
  balance: number /* int64 */;
  history: number /* int */[];
  players: Player[];
}
export interface GameStateMessage {
  type: 'game_state';
  state: GamePhase;
  winning_number?: number /* int */;
  countdown?: number /* int */;
  history: number /* int */[];
}
export interface CountdownMessage {
  type: 'countdown';
  state: GamePhase;
  seconds_remaining: number /* int */;
}
export interface BetAcceptedMessage {
  type: 'bet_accepted';
  bet_type: BetType;
  bet_value: string;
  amount: number /* int64 */;
  balance: number /* int64 */;
}
export interface BetRejectedMessage {
  type: 'bet_rejected';
  reason: string;
}
export interface ResultMessage {
  type: 'result';
  winning_number: number /* int */;
  payouts: Payout[];
  total_won: number /* int64 */;
  balance: number /* int64 */;
}
export interface BetPlacedMessage {
  type: 'bet_placed';
  user_id: string;
  player_name: string;
  bet_type: BetType;
  bet_value: string;
  amount: number /* int64 */;
}
export interface PlayerListMessage {
  type: 'player_list';
  players: Player[];
}
export interface PlayerJoinedMessage {
  type: 'player_joined';
  player: Player;
}
export interface PlayerLeftMessage {
  type: 'player_left';
  user_id: string;
}
export interface PlayerBalanceUpdatedMessage {
  type: 'player_balance_updated';
  user_id: string;
  balance: number /* int64 */;
}
export interface PlaceBetAction {
  action: 'place_bet';
  bet_type: BetType;
  bet_value: string;
  amount: number /* int64 */;
}
export interface SetNameAction {
  action: 'set_name';
  name: string;
}
export interface ReconnectAction {
  action: 'reconnect';
  user_id: string;
  name: string;
}
